### ISSUE TITLE
Token Creation didn´t work due to error

### ISSUE THREAD

**Issue by ChippuArt** [loopcreativeandy/video-tutorial-resources#1]
Hi.
thank you first for your videos. I am watching quiet a few of them and follow your guidance.

```
\Staking\Token-Creation\mpl> ts-node main.ts
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
let's name some tokens!
\node_modules\@solana\web3.js\src\connection.ts:4594
      throw new SendTransactionError(
            ^
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (C:\Users\Flori\node_modules\@solana\web3.js\src\connection.ts:4594:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\Flori\node_modules\@solana\web3.js\src\connection.ts:4553:20)
    at async Connection.sendTransaction (C:\Users\Flori\node_modules\@solana\web3.js\src\connection.ts:4541:12)
    at async Object.sendAndConfirmTransaction (C:\Users\Flori\node_modules\@solana\web3.js\src\utils\send-and-confirm-transaction.ts:31:21)
    at async main (C:\Users\Flori\Desktop\Sugargames GmbH\Staking\Token-Creation\mpl\main.ts:65:18) {
  logs: [
    'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]',
    'Program log: Instruction: Update Metadata Accounts v2',
    "Program log: panicked at 'index out of bounds: the len is 0 but the index is 0', program/src/utils.rs:857:6",
    'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 5033 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Program failed to complete
```

Do you know what might be the problem?
Kind regards,
Florian aka Chippu

**Comment by Yugen-casca** [comment]
I have the same problem. Did u find any solution??
