### ISSUE TITLE
Unable to compile TS

### ISSUE THREAD

**Issue by tj3x3x3** [loopcreativeandy/video-tutorial-resources#2]
Getting an issue when I try to run the mpl.ts file:

TSError: ⨯ Unable to compile TypeScript:
mpl.ts:50:69 - error TS2345: Argument of type '{ createMetadataAccountArgsV2: { data: { name: string; symbol: string; uri: string; sellerFeeBasisPoints: number; creators: null; collection: null; uses: null; }; isMutable: boolean; }; }' is not assignable to parameter of type 'PublicKey'.
  Type '{ createMetadataAccountArgsV2: { data: { name: string; symbol: string; uri: string; sellerFeeBasisPoints: number; creators: null; collection: null; uses: null; }; isMutable: boolean; }; }' is missing the following properties from type 'PublicKey': equals, toBase58, toJSON, toBytes, and 3 more.

50         ix = mpl.createCreateMetadataAccountV2Instruction(accounts, args);
                                                                       ~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2345 ]

**Comment by rishabh12227** [comment]
Yes me too
Any solution??

**Comment by akshatcoder-hash** [comment]
andy has released a video on this, it'll help: [video](https://youtu.be/zncJAcnV2EE)
